name: aft-legacy
channels:
  - conda-forge
  - defaults
channel_priority: strict
dependencies:
  - python=3.8
  - numpy=1.20.3
  - scipy=1.7.0
  - pandas=1.3.0
  - scikit-image=0.18.2
  - matplotlib=3.4.2
  - jupyter
  - ipykernel
  - ipympl
  - ipywidgets
  # opencv-python 4.1.1.26 is best installed via pip
  - pip
  - pip:
      - opencv-python==4.1.1.26
